---
# ansible/playbooks/configure.yml

- name: "Configure Fedora Workstation"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "../manifest.yml"
  tasks:
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: "Create users"
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ 'wheel' if item.sudoernopassword is true }}"
        state: present
      loop: "{{ users }}"
      when: "users is iterable"
    - name: "Set hostname"
      ansible.builtin.hostname:
        name: "{{ system.hostname }}"
      when:
        - "system.hostname is defined"
    - name: "Import Oh My Zsh Role"
      ansible.builtin.import_role:
        name: "gantsign.oh-my-zsh"
      when:
        - "features.ohmyzsh.managed | bool | default (false)"
