---
# ansible/playbooks/configure.yml

- name: "Configure Fedora Workstation"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "../manifest.yml"
  tasks:
    - name: "Create users"
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"
      when:
        - "users is defined and users.length > 0"
    - name: "Set hostname"
      ansible.builtin.hostname:
        name: "{{ system.hostname }}"
      when:
        - "system.hostname is defined"
    - name: "Import Oh My Zsh Role"
      ansible.builtin.import_role:
        name: "gantsign.oh-my-zsh"
      when:
        - "features.ohmyzsh.managed | bool | default (false)"
