---
timezone: "Europe/Berlin"

users:
  - username: root
#  - username: johndoe
#    sudoernopassword: true
#    ssh_authorized_keys: https://github.com/johndoe.keys
#    docker: true

# Enable/Disable Feature Management and Settings
feature_gnome_applications: false
feature_gnome_shell: false
feature_ohmyzsh: true
feature_docker: false

# Oh My Zsh
oh_my_zsh_theme: ys
oh_my_zsh_install: yes

# Docker
docker_edition: 'ce'
docker_users: "{{ users | selectattr('docker', 'defined') | selectattr('docker', 'equalto', true) | map(attribute='username') | list }}"
docker_install_compose_plugin: true
docker_install_compose: false
...
